# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
            'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
            'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
            'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

In [3]:
df_sales = pd.DataFrame(data)

df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [4]:
total_units = sum(df_sales['Units_Sold'])
print(total_units)

105

In [5]:
total_rev = sum(df_sales['Revenue'])
print(total_rev)

16000

In [6]:
avg_units = df_sales['Units_Sold'].mean()
print(avg_units)

11.666666666666666

In [7]:
avg_rev = df_sales['Revenue'].mean()
print(avg_rev)

1777.7777777777778

## Grouping Data

In [8]:
grpdta_1 = df_sales.groupby('Product')
print(grpdta_1)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002BAC6D2B230>

In [9]:
sum_units = grpdta_1[['Units_Sold', 'Revenue']].sum()
print(sum_units)

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [10]:
grpdta_2 = df_sales.groupby('Region')
print(grpdta_2)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002BAC6DD02D0>

In [11]:
mean_u_region = grpdta_2[['Units_Sold', 'Revenue']].mean()
print(mean_u_region)

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [12]:
grpdta_3 = df_sales.groupby(['Product', 'Region'])
print(grpdta_3)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002BAC6E04770>

In [13]:
sum_r_u = grpdta_3[['Units_Sold', 'Revenue']].sum()
print(sum_r_u)

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [14]:
sorted_1 = df_sales.sort_values(['Units_Sold'], ascending = True)
print(sorted_1)

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
0       A  North          10    100     1000
4       B  North          10    200     2000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [15]:
sorted_2 = df_sales.sort_values(['Revenue'], ascending = False)
print(sorted_2)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [16]:
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending = False)
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

In [17]:
product_data = {'Product': ['A', 'B', 'C'],
                'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [18]:
df_merged = df_sales.merge(df_products)
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [23]:
total_rev1 = df_merged.groupby('Category')['Revenue'].sum()
print(total_rev1)

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64